//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StayCalmBot.Properties.i18n {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StayCalmBot.Properties.i18n.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рады, что помогли.
        ///
        ///Если есть кто-то, кому тоже нужна поддержка — перешли ему ссылку на нашего бота.
        ///
        ///Мы здесь, если что.
        ///Запусти бота, когда будет нужно..
        /// </summary>
        public static string EndOfAssistance {
            get {
                return ResourceManager.GetString("EndOfAssistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Как будешь готов, возвращайся!.
        /// </summary>
        public static string HighStressLvl_EndOfExercises {
            get {
                return ResourceManager.GetString("HighStressLvl_EndOfExercises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ты сейчас испытываешь сильное напряжение. Надо прийти в себя.
        ///
        ///Выполни два упражнения. Они созданы для этой ситуации 👇.
        /// </summary>
        public static string HighStressLvl_FirstRound {
            get {
                return ResourceManager.GetString("HighStressLvl_FirstRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1️⃣ Положи ладонь на живот.
        ///
        ///2️⃣ Следи, чтобы ладонь двигалась при вдохе и выдохе.
        ///
        ///3️⃣ Медленно дыши 45 секунд.
        ///
        ///Начинай по готовности 👇.
        /// </summary>
        public static string HighStressLvl_FirstRound_Step_1 {
            get {
                return ResourceManager.GetString("HighStressLvl_FirstRound_Step_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отлично. Мы сделали базовые техники, чтобы прийти в себя.
        ///
        ///Напряжение должно было снизиться.
        ///
        ///Давай проверим..
        /// </summary>
        public static string HighStressLvl_FirstRound_Step_10 {
            get {
                return ResourceManager.GetString("HighStressLvl_FirstRound_Step_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на здесь должен быть таймер.
        /// </summary>
        public static string HighStressLvl_FirstRound_Step_2 {
            get {
                return ResourceManager.GetString("HighStressLvl_FirstRound_Step_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отлично. Твоё дыхание должно было замедлиться и стать глубже.
        ///
        ///Если нет, начни дышать медленнее.
        ///
        ///Переходи ко второму упражнению 👇.
        /// </summary>
        public static string HighStressLvl_FirstRound_Step_3 {
            get {
                return ResourceManager.GetString("HighStressLvl_FirstRound_Step_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на На первый взгляд, упражнение выглядит детским, но оно отлично работает.
        ///
        ///Пока будешь его выполнять, придёшь в себя..
        /// </summary>
        public static string HighStressLvl_FirstRound_Step_4 {
            get {
                return ResourceManager.GetString("HighStressLvl_FirstRound_Step_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Найди взглядом пять любых предметов. Назови их вслух или про себя..
        /// </summary>
        public static string HighStressLvl_FirstRound_Step_5 {
            get {
                return ResourceManager.GetString("HighStressLvl_FirstRound_Step_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прикоснись к четырём любым предметам. Назови их вслух или про себя..
        /// </summary>
        public static string HighStressLvl_FirstRound_Step_6 {
            get {
                return ResourceManager.GetString("HighStressLvl_FirstRound_Step_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Услышь три любых звука. Назови их вслух или про себя..
        /// </summary>
        public static string HighStressLvl_FirstRound_Step_7 {
            get {
                return ResourceManager.GetString("HighStressLvl_FirstRound_Step_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обрати внимание на два ощущения в своём теле (чешется ухо, занемела нога, хочется пить).
        ///
        ///Перечисли их вслух или про себя..
        /// </summary>
        public static string HighStressLvl_FirstRound_Step_8 {
            get {
                return ResourceManager.GetString("HighStressLvl_FirstRound_Step_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вспомни одно своё качество, которое тебе нравится.
        ///
        ///Назови его вслух или произнеси про себя..
        /// </summary>
        public static string HighStressLvl_FirstRound_Step_9 {
            get {
                return ResourceManager.GetString("HighStressLvl_FirstRound_Step_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ты по-прежнему в напряжении.
        ///
        ///Применим другой подход. Сделаем ещё одну технику..
        /// </summary>
        public static string HighStressLvl_SecondRound {
            get {
                return ResourceManager.GetString("HighStressLvl_SecondRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Так бывает.
        ///
        ///Давай сделаем перерыв и повторим.
        ///
        ///Отвлекись, выпей воды, выйди в другое место, поговори с кем-то, если это возможно.
        ///
        ///После этого вернись к техникам. Они работают..
        /// </summary>
        public static string HighStressLvl_SecondRound_Finish {
            get {
                return ResourceManager.GetString("HighStressLvl_SecondRound_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1️⃣ Одновременно очень сильно наморщи лоб, сморщи нос, вытяни вперёд губы.
        ///
        ///2️⃣ Удерживай сильное напряжение пять секунд.
        ///
        ///3️⃣ Потом медленно расслабь лицо..
        /// </summary>
        public static string HighStressLvl_SecondRound_Step_1 {
            get {
                return ResourceManager.GetString("HighStressLvl_SecondRound_Step_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1️⃣ Как можно выше подними плечи. Почувствуй напряжение в шее.
        ///
        ///2️⃣ Сильно, почти до боли, сожми кулаки.
        ///
        ///3️⃣ Удерживай напряжение пять секунд.
        ///
        ///4️⃣ Потом медленно расслабь плечи и руки..
        /// </summary>
        public static string HighStressLvl_SecondRound_Step_2 {
            get {
                return ResourceManager.GetString("HighStressLvl_SecondRound_Step_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1️⃣ Сильно сведи локти за спиной, почти до боли в лопатках.
        ///
        ///2️⃣ Удерживай напряжение 5 секунд.
        ///
        ///3️⃣ Потом медленно расслабь спину..
        /// </summary>
        public static string HighStressLvl_SecondRound_Step_3 {
            get {
                return ResourceManager.GetString("HighStressLvl_SecondRound_Step_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1️⃣ Очень сильно вытяни пальцы ног на себя.
        ///
        ///2️⃣ Удерживай напряжение 5 секунд.
        ///
        ///3️⃣ Потом медленно расслабь ноги..
        /// </summary>
        public static string HighStressLvl_SecondRound_Step_4 {
            get {
                return ResourceManager.GetString("HighStressLvl_SecondRound_Step_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Теперь глубоко вдохни. Ощути, как мышцы расслабились.
        ///
        ///Если ещё осталось напряжение, ты можешь повторить эту технику..
        /// </summary>
        public static string HighStressLvl_SecondRound_Step_5 {
            get {
                return ResourceManager.GetString("HighStressLvl_SecondRound_Step_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проверим, как изменилось твоё состояние..
        /// </summary>
        public static string HighStressLvl_SecondRound_Step_6 {
            get {
                return ResourceManager.GetString("HighStressLvl_SecondRound_Step_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оставь свои контактные данные, чтобы мы могли связаться с тобой.
        ///
        ///Выбери удобный для тебя способ связи👇.
        /// </summary>
        public static string Interaction_ContactDetails {
            get {
                return ResourceManager.GetString("Interaction_ContactDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Здравствуй!
        ///
        ///Мы — профессиональные психологи. Работаем в кризисных ситуациях много лет.
        ///
        ///Знаем, какие техники эффективны.
        ///
        ///Мы поможем тебе собраться с силами и справиться со стрессом.
        ///
        ///Расскажи, в какой ситуации ты находишься, и мы предложим техники, подходящие для тебя.
        ///
        ///Нажми кнопку «Дальше» и ответь на несколько вопросов👇
        ///Также вы можете вызвать оператора нажав соответствующую кнопку..
        /// </summary>
        public static string Interaction_Description {
            get {
                return ResourceManager.GetString("Interaction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сочувствуем. Тебе сейчас нелегко.
        ///
        ///Давай вместе сделаем три упражнения, чтобы снизить уровень напряжения.
        ///
        ///Для этого следуй нашим инструкциям..
        /// </summary>
        public static string MediumStressLvl {
            get {
                return ResourceManager.GetString("MediumStressLvl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хорошо. Возможно, сейчас тебе поможет переключение: выпить воды, выйти в другое место, поговорить с кем-то.
        ///
        ///Мы будем здесь, когда понадобимся..
        /// </summary>
        public static string MediumStressLvl_NotNow {
            get {
                return ResourceManager.GetString("MediumStressLvl_NotNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мы предлагаем тебе познакомиться с шестью принципами, которые в сложных условиях помогают оставаться в норме.
        ///
        ///К каждому принципу ты найдёшь рекомендацию, как его использовать.
        ///
        ///Разные принципы подходят разным людям. Выбирай те, которые тебе проще выполнять..
        /// </summary>
        public static string MediumStressLvl_Principles {
            get {
                return ResourceManager.GetString("MediumStressLvl_Principles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 🔎 Главный принцип. Обращай внимание на своё состояние.
        ///
        ///Важно знать: стресс - естественная реакция организма в ответ на любое неблагоприятное воздействие.
        ///
        ///Если ты знаешь, что испытываешь стресс, ты можешь им управлять.
        ///
        ///Как это делать?
        ///
        ///⚡Когда чувствуешь напряжение, отвлекись от дел и обрати внимание на свои ощущения.
        ///
        ///Назови эмоцию, которую ты сейчас испытываешь.
        ///
        ///🔎 Возможно, эта эмоция проявляется в теле. Где? Подумай, какие мышцы сейчас напряжены: шея, спина, лицо?
        ///
        ///Одного осознания дост [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string MediumStressLvl_Principles_1 {
            get {
                return ResourceManager.GetString("MediumStressLvl_Principles_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 🧍Второй принцип. Заботься о своём теле.
        ///
        ///Чем лучше твое физическое состояние, тем легче тебе справляться с напряжением.
        ///
        ///Старайся полноценно есть, пить, спать, отдыхать, двигаться - насколько это возможно.
        ///
        ///Тело само поможет психике оставаться в норме..
        /// </summary>
        public static string MediumStressLvl_Principles_2 {
            get {
                return ResourceManager.GetString("MediumStressLvl_Principles_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 🗓️ Третий принцип. Опирайся на привычки.
        ///
        ///Находи привычные действия, которые ты можешь совершать регулярно, даже если всё вокруг меняется.
        ///
        ///Например: каждый день пить из одной и той же кружки, заправлять постель, делать зарядку, вести дневник.
        ///
        ///Это поможет поддержать психику в работоспособном состоянии..
        /// </summary>
        public static string MediumStressLvl_Principles_3 {
            get {
                return ResourceManager.GetString("MediumStressLvl_Principles_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 🙏 Четвёртый принцип. Делай добрые дела.
        ///
        ///Каждое доброе дело увеличивает твой собственный ресурс. Это работает на физиологическом уровне.
        ///
        ///Эффективны даже самые простые действия: скажи кому-то приятные слова, сделай подарок близким, помоги соседу..
        /// </summary>
        public static string MediumStressLvl_Principles_4 {
            get {
                return ResourceManager.GetString("MediumStressLvl_Principles_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 🤝 Пятый принцип. Общайся с другими людьми.
        ///
        ///Общение необходимо человеку для поддержания психического здоровья. Можно разговаривать или просто быть рядом с кем-то.
        ///
        ///Выговаривайся, поддерживай других, просто говори на любые темы..
        /// </summary>
        public static string MediumStressLvl_Principles_5 {
            get {
                return ResourceManager.GetString("MediumStressLvl_Principles_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 🧠 Шестой принцип. Соблюдай психогигиену.
        ///
        ///1️⃣ Выдели время, когда проверять новостные источники и социальные сети.
        ///
        ///❗️Важно - не сразу после пробуждения и не перед сном.
        ///
        ///2️⃣ Не вступай в споры. Чаще всего, это бесполезно - только увеличит уровень твоего стресса.
        ///
        ///Нормально сказать: &quot;Стоп. Я это не обсуждаю&quot;..
        /// </summary>
        public static string MediumStressLvl_Principles_6 {
            get {
                return ResourceManager.GetString("MediumStressLvl_Principles_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сочувствуем, что напряжение сохраняется.
        ///
        ///Возможно, тебе нужно больше времени, чтобы упражнения подействовали.
        ///
        ///Давай сделаем их ещё раз, очень медленно. Они работают..
        /// </summary>
        public static string MediumStressLvl_Repeat {
            get {
                return ResourceManager.GetString("MediumStressLvl_Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сочувствуем, что напряжение сохраняется.
        ///
        ///Возможно, тебе нужно больше времени, чтобы упражнения подействовали.
        ///
        ///Давай сделаем их ещё раз, очень медленно. Они работают..
        /// </summary>
        public static string MediumStressLvl_RepeatExercises {
            get {
                return ResourceManager.GetString("MediumStressLvl_RepeatExercises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1️⃣ Удобно сядь или встань.
        ///
        ///2️⃣ Почувствуй пол или землю под ногами.
        ///
        ///3️⃣ Сосредоточься на ощущении плотной опоры под ногами.
        ///
        ///4️⃣ Сделай вдох носом. Обрати внимание, как воздух наполняет легкие.
        ///
        ///5️⃣ Представь, что выдыхаешь воздух через пятки в землю.
        ///
        ///6️⃣ Повтори вдох носом и выдох через пятки 7 раз..
        /// </summary>
        public static string MediumStressLvl_Step_1 {
            get {
                return ResourceManager.GetString("MediumStressLvl_Step_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хорошо.
        ///
        ///Теперь ты знаешь базовые принципы.
        ///
        ///Здесь появятся ещё упражнения и техники — напишем тебе, когда добавим.
        ///
        ///Если уровень стресса будет больше 1-5, переходи в другие разделы бота, нажав кнопку Start в Menu (рядом с полем ввода текста).
        ///
        ///Там упражнения, которые помогут прийти в себя здесь и сейчас..
        /// </summary>
        public static string MediumStressLvl_Step_10 {
            get {
                return ResourceManager.GetString("MediumStressLvl_Step_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Теперь ты ощущаешь опору.
        ///
        ///Сделаем следующий шаг.
        ///
        ///Посчитай в обратном порядке от 30 до 1 вслух или про себя.
        ///
        ///Чётко проговаривай каждое число..
        /// </summary>
        public static string MediumStressLvl_Step_2 {
            get {
                return ResourceManager.GetString("MediumStressLvl_Step_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1️⃣ Очень крепко обними себя двумя руками за плечи.
        ///
        ///2️⃣ Сосчитай до десяти и отпусти.
        ///
        ///3️⃣ Расслабь пальцы. И снова очень крепко сожми плечи.
        ///
        ///4️⃣ Сосчитай до десяти и отпусти..
        /// </summary>
        public static string MediumStressLvl_Step_3 {
            get {
                return ResourceManager.GetString("MediumStressLvl_Step_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отлично! После этих трёх упражнений уровень стресса должен немного снизиться.
        ///
        ///При этом негативные мысли и чувства могут возвращаться.  Важно замечать их, но не давать им захватить тебя.
        ///
        ///Потренируемся делать это?.
        /// </summary>
        public static string MediumStressLvl_Step_4 {
            get {
                return ResourceManager.GetString("MediumStressLvl_Step_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Эта техника поможет увидеть свою эмоцию и дать ей уйти.
        ///
        ///1️⃣ Подумай, какую негативную эмоцию ты ощущаешь? Назови её.
        ///
        ///Как это делать?
        ///
        ///⚡️Когда чувствуешь напряжение, отвлекись от дел и обрати внимание на свои ощущения.
        ///
        ///Назови эмоцию, которую ты сейчас испытываешь.
        ///
        ///🔎 Возможно, эта эмоция проявляется в теле. Где? Подумай, какие мышцы сейчас напряжены: шея, спина, лицо?
        ///
        ///Одного осознания достаточно, чтобы запустить механизмы, снижающие уровень стресса.
        ///
        ///Если хочешь, можешь помассировать и рас [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string MediumStressLvl_Step_5 {
            get {
                return ResourceManager.GetString("MediumStressLvl_Step_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2️⃣ Ощути, где она находится в твоём теле? Ты можешь чувствовать что-то похожее на напряжение, тяжесть, жжение.
        ///
        ///3️⃣ Положи руку на это место..
        /// </summary>
        public static string MediumStressLvl_Step_6 {
            get {
                return ResourceManager.GetString("MediumStressLvl_Step_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 4️⃣ Направь в это место вдох. В своём воображении окружи эту эмоцию воздухом.
        ///
        ///5️⃣ Пусть она окажется в воздушном пузыре, где не сможет тебе навредить.
        ///
        ///6️⃣ Выдохни..
        /// </summary>
        public static string MediumStressLvl_Step_7 {
            get {
                return ResourceManager.GetString("MediumStressLvl_Step_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хорошо. К этому моменту твоё ощущение стресса должно было уменьшиться.
        ///
        ///Так ли это?.
        /// </summary>
        public static string MediumStressLvl_Step_8 {
            get {
                return ResourceManager.GetString("MediumStressLvl_Step_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рады, что тебе стало легче.
        ///
        ///Если есть срочные дела, ты можешь ими заняться.
        ///
        ///Если хочешь почувствовать себя ещё спокойнее, мы можем повторить упражнения.
        ///
        ///Или можешь познакомиться с принципами поддержания своего состояния в норме..
        /// </summary>
        public static string MediumStressLvl_Step_9 {
            get {
                return ResourceManager.GetString("MediumStressLvl_Step_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оцени свой уровень стресса по шкале от 1 до 10.
        ///
        ///❗️ 9-10 — теряю контроль над своими эмоциями, не в состоянии что-то делать.
        ///
        ///⚠️ 6-8 — сильно переживаю, сложно заниматься делами из-за стресса, с этим нужно что-то делать.
        ///
        ///🟡 1-5 — в основном — нормально, могу справляться с неприятными ощущениями и мыслями..
        /// </summary>
        public static string StressLevelAssessment {
            get {
                return ResourceManager.GetString("StressLevelAssessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рады, что тебе стало легче.
        ///
        ///Если есть срочные дела, ты можешь ими заняться.
        ///
        ///Если хочешь почувствовать себя ещё спокойнее, мы можем продолжить..
        /// </summary>
        public static string Transition_FromHighToMediumLevel {
            get {
                return ResourceManager.GetString("Transition_FromHighToMediumLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рады, что тебе стало легче.
        ///
        ///Если есть срочные дела, ты можешь ими заняться.
        ///
        ///Если хочешь почувствовать себя ещё спокойнее, мы можем продолжить..
        /// </summary>
        public static string Transition_FromHighToWeakevel {
            get {
                return ResourceManager.GetString("Transition_FromHighToWeakevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При этом уровне стресса экстренные меры обычно не требуются.
        ///
        ///ℹ️ Мы предлагаем тебе познакомиться с принципами, которые помогают оставаться в норме в сложных условиях.
        ///
        ///▶️ Если же ты чувствуешь напряжение и хочешь снизить его прямо сейчас, переходи к упражнениям..
        /// </summary>
        public static string WeakStressLvl {
            get {
                return ResourceManager.GetString("WeakStressLvl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сочувствуем, что напряжение сохраняется.
        ///
        ///Возможно, тебе нужно больше времени, чтобы упражнения подействовали.
        ///
        ///Давай сделаем их ещё раз, очень медленно. Они работают..
        /// </summary>
        public static string WeakStressLvl_Repeat {
            get {
                return ResourceManager.GetString("WeakStressLvl_Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хорошо.
        ///
        ///Давай вместе сделаем три коротких техники.
        ///
        ///Для этого выполняй инструкции..
        /// </summary>
        public static string WeakStressLvl_Step_1 {
            get {
                return ResourceManager.GetString("WeakStressLvl_Step_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1️⃣ Удобно сядь или встань.
        ///
        ///2️⃣ Почувствуй пол или землю под ногами.
        ///
        ///3️⃣ Сосредоточься на ощущении плотной опоры под ногами.
        ///
        ///4️⃣ Сделай вдох носом. Обрати внимание, как воздух наполняет легкие.
        ///
        ///5️⃣ Представь, что выдыхаешь воздух через пятки в землю.
        ///
        ///6️⃣ Повтори вдох носом и выдох через пятки 7 раз..
        /// </summary>
        public static string WeakStressLvl_Step_2 {
            get {
                return ResourceManager.GetString("WeakStressLvl_Step_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Теперь ты ощущаешь опору.
        ///
        ///Сделаем следующий шаг.
        ///
        ///Посчитай в обратном порядке от 30 до 1 вслух или про себя.
        ///
        ///Чётко проговаривай каждое число..
        /// </summary>
        public static string WeakStressLvl_Step_3 {
            get {
                return ResourceManager.GetString("WeakStressLvl_Step_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1️⃣ Очень крепко обними себя двумя руками за плечи.
        ///
        ///2️⃣ Сосчитай до десяти и отпусти.
        ///
        ///3️⃣ Расслабь пальцы. И снова очень крепко сожми плечи.
        ///
        ///4️⃣ Сосчитай до десяти и отпусти..
        /// </summary>
        public static string WeakStressLvl_Step_4 {
            get {
                return ResourceManager.GetString("WeakStressLvl_Step_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отлично! После этих трёх упражнений уровень стресса должен немного снизиться.
        ///
        ///При этом негативные мысли и чувства могут возвращаться.  Важно замечать их, но не давать им захватить тебя.
        ///
        ///Потренируемся делать это?.
        /// </summary>
        public static string WeakStressLvl_Step_5 {
            get {
                return ResourceManager.GetString("WeakStressLvl_Step_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Эта техника поможет увидеть свою эмоцию и дать ей уйти.
        ///
        ///1️⃣ Подумай, какую негативную эмоцию ты ощущаешь? Назови её..
        /// </summary>
        public static string WeakStressLvl_Step_6 {
            get {
                return ResourceManager.GetString("WeakStressLvl_Step_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2️⃣ Ощути, где она находится в твоём теле? Ты можешь чувствовать что-то похожее на напряжение, тяжесть, жжение.
        ///
        ///3️⃣ Положи руку на это место..
        /// </summary>
        public static string WeakStressLvl_Step_7 {
            get {
                return ResourceManager.GetString("WeakStressLvl_Step_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 4️⃣ Направь в это место вдох. В своём воображении окружи эту эмоцию воздухом.
        ///
        ///5️⃣ Пусть она окажется в воздушном пузыре, где не сможет тебе навредить.
        ///
        ///6️⃣ Выдохни..
        /// </summary>
        public static string WeakStressLvl_Step_8 {
            get {
                return ResourceManager.GetString("WeakStressLvl_Step_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хорошо. К этому моменту твоё ощущение стресса должно было уменьшиться.
        ///
        ///Так ли это?.
        /// </summary>
        public static string WeakStressLvl_Step_9 {
            get {
                return ResourceManager.GetString("WeakStressLvl_Step_9", resourceCulture);
            }
        }
    }
}
